### PR TITLE
Release - v1.2.0

### PR DESCRIPTION
**Pull request by qgustavor**
# Release v1.2.0

<a name="changeSummary-start"></a>

- #183
- #181

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [Find and fetch (@qgustavor)](https://github.com/qgustavor/mega/pull/183)

Implement find, search and navigate functions, and fix fetch related issues.
               
#### [Add test for providing a stream as an input (@qgustavor)](https://github.com/qgustavor/mega/pull/181)

No, that's not because of the guy who doesn't read things, that's because I noticed there was not a test for that.
               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by AliAryanTech** [comment]
require() of ES Module /app/node_modules/megajs/node_modules/node-fetch/src/index.js from /app/node_modules/megajs/dist/main.node-cjs.js not supported.
Instead change the require of index.js in /app/node_modules/megajs/dist/main.node-cjs.js to a dynamic import() which is available in all CommonJS modules.

In latest version, I'd use example code

**Comment by qgustavor** [comment]
I was kinda expecting that, that's why I ran the tests, I just didn't expected that the tests would not detect that. Please, send a pull request fixing it or wait until it bothers it me so much that I fix that myself. Which can take a lot of time since I'm delayed for work at the moment and I don't even know how I could find time to answer this comment... 😑

**Comment by qgustavor** [comment]
Other option, I forgot to comment, is downgrading node-fetch back to the v2 branch which still support require(). That's why node-fetch was in v2.

**Comment by AliAryanTech** [comment]
> Other option, I forgot to comment, is downgrading node-fetch back to the v2 branch which still support require(). That's why node-fetch was in v2.

alright thanks

**Comment by qgustavor** [comment]
Ok, I just need to update documentation now.

**Pull request merged**
