### PR TITLE
Release - v1.1.1

### LINKED ISSUE #93: Run unit tests in Deno too
At the moment only integration tests are run in Deno (those which use the compiled library), not unit tests (those which load parts of the code from the source).

What is blocking this issue is how to implement it: is there a way to implement it without duplicating a lot of code that handle Node polyfills between build.js and test/helpers/test-runner.mjs?

### PR DESCRIPTION
**Pull request by qgustavor**
# Release v1.1.1

<a name="changeSummary-start"></a>

- #135
- #134
- #133
- #131

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [Housekeeping (@qgustavor)](https://github.com/qgustavor/mega/pull/135)

Rewrite tests to not leak async operations, removing the need of using `sanitizeResources: false`, and fix the test workflow.
#### [Fix Zalgo in Storage class (@qgustavor)](https://github.com/qgustavor/mega/pull/134)

1.  Added tests for checking for Zalgo.  2.  Moved email check to `.login()` so it would not run in the constructor.  3.  Added process.nextTick to avoid Zalgo.  4.
#### [Fixing tests (@qgustavor)](https://github.com/qgustavor/mega/pull/133)

Fixes #93, **an issue related to crypto that showed up in tests** and fixed Deno tests.
#### [Better error handling in API (@qgustavor)](https://github.com/qgustavor/mega/pull/131)

1.  Check response status before calling .json() and handle them properly.  2.  Emit or ignore errors instead of throwing.
               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by qgustavor** [comment]
@JAForbes Sorry, but why the Publish step didn't finished? https://github.com/qgustavor/mega/actions/runs/3766660276/jobs/6403399581

**Comment by qgustavor** [comment]
Pre-release version published: https://www.npmjs.com/package/megajs/v/1.1.1-next.1

It would be wonderful if someone can test it. I will wait some time and an answer from JAForbes (maybe I set up pr-release wrongly) before merging into main.

**Comment by qgustavor** [comment]
Weird: I cancelled the job, then ran it again, it finished in 45 seconds. First time it took more than 10 minutes then I had to cancel it manually. A second pre-release with the crypto fixes is available in npm: https://www.npmjs.com/package/megajs/v/1.1.1-next.2

**Comment by JAForbes** [comment]
Hey, not sure, it looks like you everything configured correctly.  That step is this simple:

```js
await $`npm publish --tag=${tag}`
// then node exits
```

I'll look into it but I'd probably say this is just a github actions bug.  It looks like the package [published](https://www.npmjs.com/package/megajs/v/1.1.1-next.1), there's no reason for node to not exit at that point.  I'm guessing it did exit but then the state didn't change in the actions runner.

I might add a flag to log any open handles in node and to log when node is about to exit because then you could at least rule this out as a pr-release issue.

Either way I think you can safely ignore this.  But let me know if you see it again, I'll open an issue to at track this handle logging.

**Comment by qgustavor** [comment]
I just tested the latest pre-release in a real application dealing with a lot of files and it went well. I will merge this PR in 24 hours if no one reports any issue until them.

**Pull request merged**
