### PR TITLE
Typescript types fix 

### PR DESCRIPTION
**Pull request by i0x0**
Because of some errors in the CommonJS declaration type in a TS project, it wouldn't build but it should now

### CODE REVIEW

**Review by qgustavor — COMMENTED** [review]
Are the changes to files other than types/cjs.d.ts needed? Those are more related to yarn and - while the documentation includes support for npm and yarn - I prefer using npm, so I'm not going to update yarn.lock in future releases neither use the .gitpod.yml file.

**Comment by i0x0** [comment]
thats fine not using the yarn.lock file. u can also delete the .gitpod.yml file bc i was editing that in school lol

**Comment by qgustavor** [comment]
I tried reproducing the issue by starting an empty project, installing typescript and megajs and trying to compile some code snippets. Looks like TypeScript type checking is not working correctly: it does not warn for `import { MutableFile } from 'megajs'` should happen since this class is not exported. I tried fixing this issue, without success. I wonder if the current API design makes it impossible to work a .d.ts file for it.

I will check pick the PR, merge it into master and release a new patch version.

**Comment by qgustavor** [comment]
PR cherry picked and merged: https://github.com/qgustavor/mega/commits/master

v1.0.7 was just released.

**Pull request closed without merging**
