### PR TITLE
An error was being thrown while copying data into uploadBuffer since …

### PR DESCRIPTION
**Pull request by amirparvez**
…uploadBuffer value was being set to null. It has been fixed.

### CODE REVIEW

**Comment by qgustavor** [comment]
Weird, if I recall correctly setting it to `null` at this point is just to allow the data to be garbage collected earlier, as the next `handleChunk` call will override it anyway. I don't mind setting it to a empty buffer, I would use `Buffer.alloc(0)` as I think that using `Buffer.from('')` would require an additional string decoding step... that's ok using `from`, I'm trying to overoptimize it.

In the other hand, if you having issues with `uploadBuffer` being `null` then seems `sendChunk` is being called before `handleChunk` fills the buffer. Well, I tried looking the code and found no way it would happen: `sendChunk` is called inside `handleChunk` but only after it sets `uploadBuffer`, and it's called after `source.on('data', ...)` but only after `data.copy(uploadBuffer, chunkPos)` which happens after a `handleChunk` call otherwise it would throw an error if `uploadBuffer` was `null`.

This fix only stops the error from being thrown, but don't solve the bug which is `sendChunk` being called when the buffer is not initialized. Or the error you're seeing comes from `data.copy(uploadBuffer, chunkPos)`, if so there is a race condition. Can you investigate this?

**Comment by amirparvez** [comment]
I thought the same when i read the code, i could not notice any problem with the code.

`data.copy(uploadBuffer, chunkPos)` was throwing `The "target" argument must be an instance of Buffer or Uint8Array. Received null` which was solved by just replacing null to an empty buffer. For the sake of investigating, just now, i tested my code again with uploadBuffer as null instead of an empty buffer. The weird part is that the lib is now working as expected. The more weirder part is that there has been no change in my code that interacts with the upload function. It's working fine in both scenarios when passing a pipeline or only a stream, and this confuses me.

**Comment by qgustavor** [comment]
Strange. If it was fixed I will close this pull request without merging. I hope this kind of issue don't happens again when (I hope so) this library gets rewritten using TypeScript.

At the moment I'm stressed as I found a website with lots of URLs pointing to files shared in MEGA individually and those URLs were generated with weak cryptographic keys. It's a illegal website, so I can't post it here. I tried reporting this issue on Reddit but they just copy-pasted some general advice for novices without reading my message. Their answer was dumb.

I don't know what client this website is using to upload their files - I can't get in touch with them - but either they're shooting themselves at the foot and doing something like `storage.upload({ key: Buffer.alloc(24) })` or they are using a vulnerable client that does it. I think they're using a third party client because only the most recent files of them use the new mega.nz domain, files from June still use the mega.co.nz domain. I don't know why someone would make a client that uses `Buffer.alloc(24)` as keys (or use this library to do that), as it practically is the same as disabling file encryption, hurting user privacy. I mean, you can do that with megajs, but then you would be shooting yourself at the foot, it is not the standard behavior of the library.

If some client is intentionally making MEGA security weaker then I need to know which client is it, report this issue privately and if they don't fix it in a month, make this report public so people can avoid it. If I can't find what client they're using the only choice I have is reporting this issue directly to MEGA (which will be bad for the illegal website as they probably will lost their accounts).

**Comment by amirparvez** [comment]
Yes, it is fixed. This request can now be closed. If it happens again and i learn something related to it i will make sure to share that and it will be great if this security issue gets solved without much hurdle.

**Pull request closed without merging**
