### PR TITLE
Release - v1.3.1

### PR DESCRIPTION
**Pull request by qgustavor**
# Release v1.3.1

<a name="changeSummary-start"></a>

- #211
- #209
- #210
- #208
- #207
- #206
- #204
- #202
- #200

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [Simplify handleForceHttps (@qgustavor)](https://github.com/qgustavor/mega/pull/211)

Use `globalThis.isSecureContext`.  Advantages and disadvantages shown in detail [here](https://github.com/qgustavor/mega/issues/205#issuecomment-2333901645).
#### [Handle `ssl` in API's pull request so Storage works in browsers (@qgustavor)](https://github.com/qgustavor/mega/pull/209)

Should fix issue #205 where the Storage class does not work on HTTPS websites.
#### [Fix .filter implementation (@qgustavor)](https://github.com/qgustavor/mega/pull/210)

It was calling .find instead of calling .filter to recurse directories.
#### [Add a note about updating TypeScript types (@qgustavor)](https://github.com/qgustavor/mega/pull/208)

I always forget about that, so is better to put it in the readme.
#### [Fix Deno tests (@qgustavor)](https://github.com/qgustavor/mega/pull/207)

--allow-net should not include a trailing slash.
#### [TS fix: find,filter,navigate in `storage` (@xmok)](https://github.com/qgustavor/mega/pull/206)

I'm not sure if the return type of `navigate` is correct - could anyone verify?.
#### [Improve bug report template (@qgustavor)](https://github.com/qgustavor/mega/pull/200)

               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by qgustavor** [comment]
I guess we can wait to #205 to be fixed before releasing v1.3.1, right?

About the error in the Deno test integration, it was not an error in the library itself but in Deno somehow:

<details><summary>Snippet of the error log</summary>

```
[rest of the log skipped]
Tests will use this directory: /tmp/megajs-tests-1940-A3ZVCxjTEaB0

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.46.2
Args: ["deno", "test", "--allow-env=MEGA_MOCK_URL", "--allow-net=127.0.0.1:44079/"]

thread 'main' panicked at cli/args/flags.rs:5078:60:
called `Result::unwrap()` on an `Err` value: ErrorInner { kind: InvalidValue, context: FlatMap { keys: [], values: [] }, message: Some(Raw("invalid port in '127.0.0.1:44079/': '44079/'")), source: None, help_flag: None, styles: Styles { header: Style { fg: None, bg: None, underline: None, effects: Effects() }, error: Style { fg: None, bg: None, underline: None, effects: Effects() }, usage: Style { fg: None, bg: None, underline: None, effects: Effects() }, literal: Style { fg: None, bg: None, underline: None, effects: Effects() }, placeholder: Style { fg: None, bg: None, underline: None, effects: Effects() }, valid: Style { fg: None, bg: None, underline: None, effects: Effects() }, invalid: Style { fg: None, bg: None, underline: None, effects: Effects() } }, color_when: Never, color_help_when: Never, backtrace: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Deno tests exited with code 1
```

</details>

**Comment by xmok** [comment]
Fantastic troubleshooting in the aforementioned Issue. In the meantime I'll make another PR soon with some more missing TS types. I found a few more so I'll lump them into manageable PRs rather than one-liners. Hopefully that will be in time for the new release, as well 😄.

**Comment by qgustavor** [comment]
That's fine, I'm really grateful you are helping in this project! 😄

**Comment by qgustavor** [comment]
I need to fix the Deno tests: from the error log that's just something wrong in the arguments to "deno test" in the test runner which includes a forward slash with the port number.

**Comment by qgustavor** [comment]
This PR will be pushed after #211 gets voted by the community either in the PR itself or [here](https://github.com/qgustavor/mega/issues/205#issuecomment-2333901645). If no one votes in 72 hours I will just push it since #210 is a critical bug for me.

**Pull request merged**
