### PR TITLE
Bug fixing and new features

### PR DESCRIPTION
**Pull request by qgustavor**
Opening a pull request so changes can be reviewed. @paulcarroty and @Fromclaszureme, are you OK with those changes?

file.js changes:
- decryptAttributes doesn't accept a callback anymore, it was a synchronous function after all; errors should be handled using try/catch (related to issue #35)
- export bandwidth time limit (so it can be better handled by clients)
- close single streams if requested ([example usage](https://github.com/qgustavor/direct-mega/blob/3817ef62b0585a560cc6f9c40a8149aebaee8f29/src/sw.js#L228))
- remove "garbage removal" while decrypting (issue #35)

mutable-file.js changes:
- add importFile function (issue #19)

storage.js changes:
- handle file decryption errors and emit a event when it happens (issue #35)
- implement getAccountInfo (issue #34)

### CODE REVIEW

**Comment by qgustavor** [comment]
@Fromclaszureme Removing the `.replace(/\0|[^}]*$/g, '')` part makes it behave like the original web client, so I don't know why it's a "temporary fix". By the way, can you check if this fix works for you?

**Comment by Fromclaszureme** [comment]
@qgustavor No, some folders are still undefined; if you want i can give you an account with that issue

**Comment by qgustavor** [comment]
@Fromclaszureme Contact me via gmail or skype (my nick is qgustavor on those). You can try to find the bug: the first thing I would do is getting the value of `at.toString()` [here](https://github.com/qgustavor/mega/blob/be51143b43d1449adaa19ba76aa2cd726834610a/lib/file.js#L332).

**Comment by qgustavor** [comment]
@Fromclaszureme I just saw your edit. If it's returning "error decrypting attributes" then maybe it's a error in the crypto modules. You can also share the folder is bugged (in other client) and send me the link (here or via email).

**Comment by qgustavor** [comment]
No response. This is going to make things harder for me... maybe I will do some fuzz testing on this library.

**Comment by DeltaEvo** [comment]
I'm interested in `close single streams if requested` feature, will this PR get merged soon ?

**Comment by qgustavor** [comment]
@DeltaEvo As @Fromclaszureme stopped responding I don't know if the changed I did fixed their issues. I can fix it with a "cannot reproduce" and merge it anyway.

In the other hand I can check MEGA code and try to find where is the difference between [the original implementation](https://github.com/meganz/webclient/blob/87b95c419400269963261cf80ddf77d38101445c/nodedec.js#L655) and [this one](https://github.com/qgustavor/mega/blob/3daa01b355c311c81d386a3f7be73ceeb9d3bd22/lib/file.js#L320). Sadly this week I'm too busy for that. :confused: 

Can you check this? If not I will just merge it, build it and update the NPM package.

**Comment by DeltaEvo** [comment]
I have an account that seems to have the same issue as @Fromclaszureme  (I'm sorry I have a lot of crap on it)

#### Output from mega (Original version by tonistiigi)
<details>
  <summary>Click to expand</summary>

  ```javascript
[ 'OpenGL-2.1.6.jar',
  'OpenGL2.zip',
  'world.zip',
  'ParticlesEffects.zip',
  'web.zip',
  'JVultr-all-1.0.jar',
  'WarOfLegionsQuests.zip',
  'AresCommons-obfuscate.jar',
  'spigot.zip',
  'PersistanceGenerator-1.0.0.jar',
  'PersistanceGenerator-1.0.0.zip',
  'Teams.zip',
  'nbt.zip',
  'www.rar',
  'SamaGamesAPI.zip',
  'test.html',
  '20160904_190029.jpg',
  'epicube_website-master-56788978667890.zip',
  'build.zip',
  'haperyfac.zip',
  'NameReplacer-1.0.jar',
  'NameReplacer.zip',
  'affiche emc.xcf',
  'affiche emc.jpg',
  'Camera Uploads',
  '42_invitation.pdf',
  'security_ebooks.zip',
  'ebook.zip',
  'practical-vim-second-edition_p2_0.epub',
  undefined,
  'iframes.m3u8',
  'segment-100.ts',
  'segment-101.ts',
  'Shokugeki_no_Souma_01.mp4',
  undefined,
  undefined ]
```

</details>

#### megajs 0.13.2
<details>
  <summary>Click to expand</summary>

```javascript
[ 'OpenGL-2.1.6.jar',
  'OpenGL2.zip',
  'world.zip',
  'ParticlesEffects.zip',
  'web.zip',
  'JVultr-all-1.0.jar',
  'WarOfLegionsQuests.zip',
  'AresCommons-obfuscate.jar',
  'spigot.zip',
  'PersistanceGenerator-1.0.0.jar',
  'PersistanceGenerator-1.0.0.zip',
  'Teams.zip',
  'nbt.zip',
  'www.rar',
  'SamaGamesAPI.zip',
  'test.html',
  '20160904_190029.jpg',
  'epicube_website-master-56788978667890.zip',
  'build.zip',
  'haperyfac.zip',
  'NameReplacer-1.0.jar',
  'NameReplacer.zip',
  'affiche emc.xcf',
  'affiche emc.jpg',
  null, // Little null here
  '42_invitation.pdf',
  'security_ebooks.zip',
  'ebook.zip',
  'practical-vim-second-edition_p2_0.epub',
  'data.txt',
  'iframes.m3u8',
  'segment-100.ts',
  'segment-101.ts',
  'Shokugeki_no_Souma_01.mp4',
  'Shokugeki_No_Souma_1.webm',
  'Shokugeki_No_Souma_1vp8.webm' ]
```

</details>

#### This pr

<details>
  <summary>Click to expand</summary>

 ```javascript
/tmp/lol/megajs/dist/main.node-cjs.js:1579
    throw Error('Attributes could not be decrypted with provided key.');
    ^

Error: Attributes could not be decrypted with provided key.
    at Function.File.unpackAttributes (/tmp/lol/megajs/dist/main.node-cjs.js:1579:11)
    at MutableFile.decryptAttributes (/tmp/lol/megajs/dist/main.node-cjs.js:1246:17)
    at MutableFile.loadMetadata (/tmp/lol/megajs/dist/main.node-cjs.js:1238:14)
    at new MutableFile (/tmp/lol/megajs/dist/main.node-cjs.js:1615:13)
    at Storage._importFile (/tmp/lol/megajs/dist/main.node-cjs.js:2471:38)
    at /tmp/lol/megajs/dist/main.node-cjs.js:2410:25
    at Array.forEach (<anonymous>)
    at /tmp/lol/megajs/dist/main.node-cjs.js:2409:20
    at Request._callback (/tmp/lol/megajs/dist/main.node-cjs.js:1123:9)
    at Request.self.callback (/tmp/lol/megajs/node_modules/request/request.js:186:22)
```

</details>


So it's not resolved ... but I have a test case, I will look at this :heart:

**Comment by qgustavor** [comment]
Seems I can't merge it because it makes the situation worse. Can you send me a link of this folder? (here, via email or skype)

**Comment by DeltaEvo** [comment]
https://mega.nz/#F!o9MgSQRQ!VSpPXl7whXjayionikeX7w

**Comment by qgustavor** [comment]
Strange: I opened this file on Direct MEGA (so I can use Chrome debugger) and it opened 5 files. I checked network tab and in the API response there's 6 nodes (the folder and the 5 files).

Is this one the folder with a file which cannot be opened?

**Comment by DeltaEvo** [comment]
Yes it's it @qgustavor, but I also noticed that sometimes It works and sometimes not, very strange

**Comment by qgustavor** [comment]
Can you try to get the value of `at` before null bytes are removed on [this function](https://github.com/qgustavor/mega/blob/3daa01b355c311c81d386a3f7be73ceeb9d3bd22/lib/file.js#L320) for the files which don't work?

I think two possibilities:

* There's an error on decryption code, in this case the value of `at` must reassemble random data; in this case it's harder to fix, as there's already test cases to check if crypto is working (and, as you can see, those are passing);
* Or there's an error on the depadding code: tonistiigi's code work by removing null bytes from the end, mine and meganz code works by reading until the first null byte, so if there's a null byte in the JSON object only tonistiigi's code will read it, in ther other hand I think it's not possible have a valid JSON with a null byte on it.

**Comment by DeltaEvo** [comment]
@qgustavor it's an error on decryption code, i tried to use the browser crypto implementation but with no results

**Comment by qgustavor** [comment]
Do you used the browser implementation via Storage or File? IIRC I never tested the browser implementation of Storage. Last time I tested it wasn't working. I never urged to fix that because in the wiki there's ["don't use Storage in a web page."](https://github.com/qgustavor/mega/wiki/Security-Model).

**Comment by DeltaEvo** [comment]
I just used the browser crypto implementation in node (because this look like to be the same implementation as tonistiigi mega library)

PS: I just tried with tonistiigi crypto code, and I have the same result :cry:

**Comment by DeltaEvo** [comment]
But the fact that sometimes it successfully ran (and the test bellow) make me thinking that the decryption is not the problem here

To have this random behavior, the only thing I see that could be the error, is something that come from the network :thinking:

**Comment by qgustavor** [comment]
Those errors happened in browser or in Node? If it's in browser then maybe it's a bug in [request.js](https://github.com/qgustavor/mega/blob/master/browser/request.js). If it's the case maybe a solution is replacing it with a maintained library.

**Comment by DeltaEvo** [comment]
It's in node
I will try tomorrow to do a `git bisect` to find the commit that introduced this regression

**Comment by DeltaEvo** [comment]
@qgustavor sorry to get so long, I've runned the git bisect without success :disappointed:  but after some debugging ... I found the bug :tada: 

The bug come from here https://github.com/qgustavor/mega/blob/master/lib/crypto/index.js#L102, the buffer is not filled completly if key is smaller than 32 bytes (in my case it's 16 bytes long) , so using `allocUnsafe` here could add us some random bytes in the buffer and so make the key different (this explain the randomness of this bug), the fix is simple: use `alloc` to fill the buffer with 0

I think we can change it in `mergeKeyMac` too

**Comment by qgustavor** [comment]
Some reason the tests aren't passing on Node 10 then I'm trying to update all dependencies in order to make it work on it, causing to the build to break on my computer.

But I will merge that PR.

**Comment by qgustavor** [comment]
I published 0.13.3 with the changes of this branch. I will create other branch in order to fix the tests which are failing on Node 10 and update the build process (like replacing babel-preset-latest with babel-preset-env).

**Pull request merged**
